# Problem Set 1 
By: Leslie Trigoura


1.  Consider an electron in a 1-D box of length $L=1$ nm that has energy eigenstates given by 
\begin{equation}
\psi_n(x) = \sqrt{2} {\rm sin}(n \pi x)
\end{equation}
when $x$ has units of nanometers.  Now consider that an atomically-precise hammer is used to deform the bottom of the box such that the electron feels an effective potential given by 
\begin{equation}
V(x) = V(x)= -2(x-0.5)^3+0.5.
\end{equation}

    a.  Compute the energy expectation value of an electron described by $\psi_1(x)$ after the box is deformed.



# Answer to Question 1a:

In [2]:
import numpy as np

# Length = 1nm (SI Units)
L = 1e-9

# Mass of Electron (SI Units) # Google mass
m_e = 9.10938356e-31

# hbar (SI Units) 
hbar = 1.054571e-34

# E1 (SI Units)
E1 = np.pi **2 * hbar**2 / (2 * m_e * L**2)

print("E1 is equal to", E1, "J")


E1 is equal to 6.024658153557057e-20 J


**NOTE: PDF Document has rest of calculations for Question #1!**

 b.  Explain if you think the original energy eigenstates, $\psi_n(x)$, are stationary 
states in the deformed box.  

# Answer to Question 1b:

Answer on PDF submitted. 

2.  Considering the modified box in Question 1, write down the Hamiltonian operator after the box has been modified.  Using this Hamiltonian, use the linear variational method and a basis of the first 3 energy eigenstates of the ordinary particle in a box to estimate the ground state energy of the modified system.

In [36]:
# Same variables as above in question 1...
m = m_e # from above, simplified
x = np.linspace (0, L, 400)

V_x = - 2 * (x - 0.5e-9)**3 + 0.5e-9

def H_ij (i, j, x_array):
    dx = x_array[1] - x_array[0]
    # define 1st part of equation (diagonalized)
    psi_ii = np.sqrt(2 / L) * np.sin (i * np.pi * x_array / L)
    # define 2nd part of equation (out of diagonal)
    psi_ij = np.sqrt(2 / L) * np.sin (j * np.pi * x_array / L)
    
    G = psi_ii * V_x * psi_ij # Use G to represent integrand
    V_int = 0
    
    # Use rectangle rule approx. like in class...
    for i in range (0,len(x_array)):
        V_int = V_int + G[i] * dx
     
    if (i==j):
        E_i = np.pi**2 * hbar**2 * i**2 / (2* m *L**2)
    else:
        E_i = 0
        
    return (E_i + V_int)

H_mat = np.zeros ((3,3))
for i in range (1,4):
    for j in range (1,4): 
        H_mat [i-1][j-1] = H_ij (i,j, x)        
print (H_mat)

E_opt, c_opt = np.linalg.eig(H_mat)
    
    
print("Est. Ground State Energy is equal to ", np.min(E_opt), "J")

    

[[ 5.00000000e-10  1.48162869e-27  1.94817089e-26]
 [-4.69863798e-26  5.00000000e-10 -3.70149314e-26]
 [ 3.88687545e-26 -2.40902343e-26  5.00000000e-10]]
Est. Ground State Energy is equal to  4.999999999999998e-10 J


3.  The predecessor to Hartree-Fock theory was the Hartree method, where the main difference is that the Hartree-Fock method includes anti-symmetry in the trial wavefunction by writing it as a Slater Determinant, while the Hartree method uses a simple product wavefunction that does not capture anti-symmetry.  In particular, for a minimal-basis model of H$_2$, the Hatree method's trial wavefunction is given by
\begin{equation}
\Psi_H = \phi_1(x_1) \phi_2(x_2)
\end{equation}
while the Hartree-Fock trial wavefunction is given by 
\begin{equation}
\Psi_{HF} = \phi_1(x_1) \phi_2(x_2) - \phi_1(x_2) \phi_2(x_1),
\end{equation}
where $\phi_1$ and $\phi_2$ are molecular orbitals, and $x_1$ and $x_2$ denote the coordinates
of electron 1 and electron 2, respectively.

    Write an expression for the total energy expectation values of $\Psi_H$ and $\Psi_{HF}$ in terms of 1- and 2-electron integrals and comment on the differences.  In particular, which method do you think will yield the lower total energy?  Recall the Hamiltonian operator can be written in terms of 1- and 2-electron operators as
\begin{equation}
\hat{H} = \sum_{i}^N \hat{h}_i + \sum_{i>j}^N \hat{V}_{i,j},
\end{equation}
    where $\hat{h}_i$ is the 1-electron operator for electron $i$ and $\hat{V}_{i,j}$ is the 2-electron operator for electrons $i$ and $j$.

4. Use the following function as a trial wavefunction for the particle-in-a-box groundstate:
\begin{equation}
\phi(x) = c_1 x (L - x) + c_2 x (L-x)^2 + c_3 x^4(L-x) + c_4 x^2(L-x)^2.
\end{equation}
Compare the energy expectation value of $\phi(x)$ to $\psi_1(x)$, the true ground state of the particle in a box of length $L$.  Discuss whether or not this result is consistent with the Variational principle.

5.  The energy expression for second-order Moller-Plesset Perturbation Theory is 
\begin{equation}
E_{MP2} = 2 \sum_{i,j,a,b}^N \frac{\langle ij | V | ab \rangle \langle ab | V | ij \rangle}{\epsilon_i + \epsilon_j - \epsilon_a - \epsilon_b} - \sum_{i,j,a,b}^N \frac{\langle ij | V | ab \rangle \langle ab | V | ji \rangle}{\epsilon_i + \epsilon_j - \epsilon_a - \epsilon_b}
\end{equation}
where $N$ is the number of molecular orbitals, $\epsilon_p$ is the molecular orbital energy
of orbital $p$, and $\langle pq | V | rs \rangle$ is the 2-electron integral
involving orbitals $\phi_p, \phi_q, \phi_r$, and $\phi_s$.  

**Explain how the computational cost of evaluating the MP2 energy scales with the number of molecular orbitals.**  